- kcidb/io_schema.py
Some test suites use dashes in test case names, so to avoid having to
mangle them and use their original names allow "-" dashes in the test
paths in the schema.
Signed-off-by: Guillaume Tucker <guillaume.tucker@collabora.com>
> kcidb.io_schema: allow "-" characters in test path

- kcidb/__init__.py
Not only flatten the "misc" fields, but also convert the values to
BigQuery representation in Client.submit(). This fixes flattening deeper
"misc" fields, such as in test environments.
> Convert dictionary values in submit()

- kcidb/db_schema.py
- kcidb/io_schema.py
Add a "compiler" field to the build schema with description.  This is
a plain string to identify the compiler used with its version.
Signed-off-by: Guillaume Tucker <guillaume.tucker@collabora.com>
> schema: add compiler field to build

- kcidb/__init__.py
To avoid modifying the data passed to kcidb.Client.submit(), copy both
dictionaries and lists before modifying them.
> submit: Copy referenced data before modifying

- kcidb/db_schema.py
- kcidb/io_schema.py
Add new config_name and config_url fields for describing kernel config
options (aka defconfig) used to build the kernel, and providing a URL
to reference the full config file.
Signed-off-by: Kevin Hilman <khilman@baylibre.com>
> schema: add config_name, config_url

- .travis.yml
- .yamllint
- kcidb/__init__.py
- kcidb/tests_schema.py
- setup.py
- tests.yaml
Add tests catalog stored in "tests.yaml" file.
Add a tool for validating it, called "kcidb-tests-validate", and a tool
for printing a flat list of tests, called "kcidb-tests-list". The former
will not only validate the YAML syntax and the schema, but will also
check if test homepages are reachable (if you specify the -u/--urls
option). The latter could be useful for e.g. checking if names in your
CI system match the kcidb names correctly.
I'm hesitating to just move the database into the Python code at this
moment, but maybe we'll do that eventually.
> Add tests catalog

- README.md
- kcidb/__init__.py
- kcidb/io_schema.py
- setup.py
Beside a few small fixes, this mainly deals with separating the user and administrator interfaces. The former is abstracted from the implementation and only has two operations ("submit" and "query"), while the latter goes (will go) into details and deals with infrastructure directly.
> Separate user and admin interfaces

- kcidb/__init__.py
- kcidb/db/__init__.py
- kcidb/io/schema/__init__.py
- kcidb/io/schema/misc.py
- kcidb/io/schema/v1.py
- kcidb/mq/__init__.py
- setup.py
To prepare for addition of another major version of the schema and the
transition path, add support for multiple schema versions and inheriting
older-version data.
> Support multiple schema versions

- README.md
- kcidb/__init__.py
- kcidb/db/__init__.py
- setup.py
Support specifying ID LIKE patterns for all report object types when
querying. Support requesting all linked parents and/or children as well.
This concerns both `kcidb-db-query` and `kcidb-query` tools. The latter
becomes an actual alias to the former for the current implementation.
This also concerns the kcidb.Client.query() function, although nothing
uses it yet.
Since LIKE patterns are not very efficient compared to unconditional
queries and since interface becomes non-trivial, add `kcidb-db-dump`
tool which does exactly what `kcidb-db-query` did before - just dump the
complete database.
> Support query parameters

- tests.yaml
kdump is now a suite of tests as we are onboarding new tests which
are part of kdump, change the url to point to the top level directory
to make it apparent that it's now a suite.
> move kdump url to top level

- kcidb/io/schema/test_v3.py
- kcidb/io/schema/v3.py
- kcidb/test_misc.py
- kcidb/test_oo.py
- kcidb/test_subscriptions.py
Rename git_repository_commit* revision fields to git_commit*, in v3 I/O schema.
Fixes #85.
> io.schema: Remove "repository" from "commit"

- kcidb/__init__.py
- kcidb/misc.py
- kcidb/tests/__init__.py
Instead of printing just the latest exception, print the whole exception context stack when printing errors. This gives the full context to the user, and most importantly produces schema validation errors for *all* schema versions not only the oldest one, which is often just about the version mismatch.
> Print full exception stack on errors

- main.py
Forward merged data to the "loaded" queue in kcidb_load_queue, instead
of forwarding the original separate messages. This can help us fit under
the BigQuery query limit until we switch to another database. Note that
this might exceed the PubSub message size limit, though.
> main: Forward merged data

- kcidb/__init__.py
- kcidb/mq/__init__.py
- kcidb/test_mq.py
- main.py
- test_kcidb.py
Return publishing "futures" whenever publishing to a message queue, and
use that to make sure the messages actually got there. Output the
resulting publishing IDs in command-line tools. This fixes sporadic
message loss, especially with JSON streams.
> Provide and use a way to wait for publishing

- tests.yaml
RH recently onboarded a new watchdog timer test, please add this
test description to the KCIDB catalog.
> Add watchdog timer test to kcidb catalog

- tests.yaml
RH recently onboarded two storage block tests, one for filesystem fio and other for queue scheduler, please add this test descriptons to the KCIDB catalog.
> Add storage block fs fio and queue scheduler tests to kcidb catalog

- kcidb/__init__.py
- kcidb/db/__init__.py
- kcidb/test_db.py
- test_kcidb.py
Remove support for querying database objects using ID LIKE patterns,
since nobody uses that.
> Remove support for querying with ID LIKE patterns

- requirements.txt
- setup.py
Update to our fork of jq rebased on the upstream 1.1.2 release, also
using a PEP 440-compliant version number, which fixes installation with
recent pip versions.
> Update to stream-enabled jq 1.1.2 with fixed version

- kcidb/__init__.py
- kcidb/db/__init__.py
- kcidb/db/bigquery/__init__.py
- kcidb/db/bigquery/schema.py
- kcidb/db/misc.py
- kcidb/db/null/__init__.py
- kcidb/oo/data/__init__.py
- kcidb/test_db.py
- test_kcidb.py
Separate the notion of a database client and a database driver, allowing
adding suport for other databases except BigQuery. Add a dummy driver
called "null" which just discards all data and returns nothing when
dumping or querying.
Change the client to using a single "database specification string"
instead of the BigQuery's dataset name and project ID. The database
specification string should consist of the name of the database driver
to use, followed by a colon, followed by the driver parameter string.
Make the BigQuery driver accept the <PROJECT_ID>.<DATASET> string as its
parameters. Make it accept just the <DATASET> as well.
So instead of specifying this when creating the client:
project_id="kernelci-production", dataset="kernelci04"
you would need to specify this: …
> Separate db client and drivers

- kcidb/mq/__init__.py
Configure message queue publisher client to block if submission queue is
full. This fixes the "Deadline Exceeded" error happening when there's a
lot of big messages submitted quickly.
> mq: Block on submission overflow

- kcidb/mq/__init__.py
- requirements.txt
- setup.py
The API wasn't upgraded completely, and the cloud functions throw errors
like this:
TypeError: pull() takes from 1 to 2 positional arguments but 3
positional arguments (and 1 keyword-only argument) were given
The API usage needs to be reviewed carefully and all changed calls
updated and tested.
This reverts commit ef70ebdd8f963271626f6b7ea9ae4c3c4f2262ea.
> Revert "Upgrade google-cloud pubsub"

- kcidb/orm/__init__.py
- kcidb/test_orm.py
- requirements.txt
- setup.py
Switch to using the I/O schema with resource/checkout/build/test defined
inside the top-level $defs property and referenced from there, instead
of duplicated throughout the schema.
Concerns kernelci/kcidb-io#11
> Use I/O schema with $defs

- kcidb/__init__.py
- test_kcidb.py
Depends-on: kernelci/kcidb-io#37
Closes: #78
Signed-off-by: Paweł Wieczorek <pawiecz@collabora.com>
> Allow validation against specific schema version

- kcidb/__init__.py
- kcidb/misc.py
- requirements.txt
- setup.py
- test_kcidb.py
Support specifying the schema's major version to kcidb-upgrade, so
upgrades could be done to older schema versions.
Fixes #79
> Support specifying schema version to kcidb-upgrade

- README.md
- SUBMISSION_HOWTO.md
- doc/_index.md
- doc/administrator_guide.md
- doc/developer_guide.md
- doc/installation.md
- doc/submitter_guide.md
Reorganize the documentation to enable its inclusion into the
Hugo-generated docs on the KernelCI website.
Extract the installation and the developer guide sections into their own
files. Put all the documentation files into the "doc" directory, and
adjust whatever links are there to work under Hugo (but unfortunately
not with GitHub rendering, or with manual following). Add front matter
to every documentation file, and adjust headers to work with headers
added by Hugo.
Add a bunch of updates and improvements before doing the above.
> Restructure docs for KernelCI website

- kcidb/monitor/__init__.py
- kcidb/monitor/output.py
- kcidb/monitor/spool/__init__.py
- kcidb/monitor/test_output.py
- kcidb/test_monitor.py
Do not render the notification message before we know it wasn't sent already. I.e. first create the doc atomically, then render the message and store it there.
This avoids the overhead of rendering messages for notifications which were already sent. E.g. for a revision subscription, which sent its notification on the arrival of its first failed test, but would trigger on every next test arriving, because it already has a failed one.
> monitor: Do not render messages repeatedly

- kcidb/monitor/spool/__init__.py
Switch back to creating the message in the spool in one go, since our
message-sending Cloud Function is triggered off new objects being
created, and risks getting triggered off an incomplete object, if it's
created in two steps.
We would still need to avoid rendering messages repeatedly, but with the
current (very dumb) ORM caching it's not so critical.
This reverts commit b1d916642876d5d16869f6b41219f0158a237652.
> Revert "monitor: Do not render messages repeatedly"

- cloud
Double the memory allocated for the notification-spooling Cloud
Function, since it's been running out of memory recently.
> cloud: Double memory for kcidb_spool_notifications

- .pylintrc
- kcidb/__init__.py
- kcidb/db/__init__.py
- kcidb/db/bigquery/__init__.py
- kcidb/db/json/__init__.py
- kcidb/db/misc.py
- kcidb/db/null/__init__.py
- kcidb/db/sqlite/__init__.py
- kcidb/io.py
- kcidb/misc.py
- kcidb/monitor/test_output.py
- kcidb/mq/__init__.py
- kcidb/orm/__init__.py
- kcidb/test_db.py
- kcidb/test_monitor.py
- kcidb/test_mq.py
- kcidb/test_orm.py
- main.py
- requirements.txt
- setup.py
- test_kcidb.py
Record the currently-used schema version in the new `kcidb.io` module.
Concerns #155
Provides support to #289, which can now use `kcidb.io.SCHEMA` to refer to the object for the currently-used schema version.
@mharyam, please review.
> Record currently-used schema version in kcidb.io module

- cloud
- kcidb/test_monitor.py
- main.py
Our BigQuery querying costs are overwhelming. Add support for disabling posting updates about loaded data, which effectively disables generating notifications and dramatically reduces amount of BigQuery queries.
> Support disabling posting updates about loaded data

- cloud
Bump the kcidb_load_queue() function memory limit again, to 1GB, to try
to deal with it getting killed due to memory use.
If this doesn't help we'll have to actively look for memory spikes,
likely in psycopg2 use.
> cloud: Bump load_queue function memory again

- kcidb/orm/__init__.py
Instead of using the hardcoded "id" as the field containing the object ID, interrogate the schema's object type for its ID field names, when generating ORM patterns from I/O data.
> orm: Do not hardcode ID field names

- .github/workflows/test.yml
Force using an older Ubuntu release which still supports Python 3.6 to keep testing it.
> Actions: Force older Ubuntu with Python 3.6

- kcidb/__init__.py
The documentation for submit() says that it needs to be passed JSON, making a bit ambiguous if this means a Python JSON object or the rendered JSON.  Explicitly say that the former is required.
> submit: Clarify that we are submitting a JSON object

- cloud
- kcidb/db/postgresql/v04_00.py
- kcidb/misc.py
- kcidb/mq/__init__.py
- kcidb/orm/__init__.py
- kcidb/test_orm.py
- main.py
Limit the number of object IDs per pattern, not number of patterns, as those can still get arbitrarily large, and limiting them doesn't have the effect of limiting the load on the spooling Cloud Function we aimed for.
> main: Limit number of objects per pattern

- doc/installation.md
- doc/submitter_guide.md
These changes will allow users to download the main branch instead of latest version.
@spbnick Need reviews.
Fixes #353
> Doc: Removing release mentions

- kcidb/tests/__init__.py
Ignore SSL errors (such as invalid or expired certificate) when validating the test catalog, since we're only verifying that the resource is there, and because that happens sometimes due to neglect, and not because the test's website went away. Otherwise our CI breaks.
> tests: Ignore SSL errors when validating

- .gitignore
- kcidb/monitor/subscriptions/nikolai_kondrashov.py
Now that we have tests for actual deployments, we don't really need the
test subscription for Nikolai Kondrashov enabled. Let's disable it and
reduce the SPAM.
> monitor: Disable Nikolai Kondrashov's subscription

- kcidb/db/__init__.py
- kcidb/test_db.py
The tests functions in kcidb/test_db.py switched from using mocks to pytests fixtures  and the database initialized in the client object constructor in kcidb/db/__init__.py to store its own database attribute @spbnick
> switch from mocks to pytest fixtures

- kcidb/__init__.py
- kcidb/db/__init__.py
- kcidb/db/abstract.py
- kcidb/db/bigquery/v04_00.py
- kcidb/db/postgresql/v04_00.py
- kcidb/db/schematic.py
- kcidb/db/sqlite/v04_00.py
- kcidb/monitor/test_output.py
- kcidb/mq/__init__.py
- kcidb/oo/__init__.py
- kcidb/orm/__init__.py
- kcidb/orm/data.py
- kcidb/orm/query.py
- kcidb/test_db.py
- kcidb/test_monitor.py
- kcidb/test_mq.py
- kcidb/test_oo.py
- kcidb/test_orm.py
- main.py
Extracted `Schema` and `Pattern` class and their dependencies and made them as a separate module from kcidb.orm module.
This PR closes #386 
@spbnick Need reviews.
> Break down kcidb.orm module

- doc/administrator_guide.md
This will ensure the user installs the PostgreSQL before trying to deploy the application.
closes #414
> Docs : add psql installation in administrator_guide

- .github-workflow-script
- .github/workflows/test.yml
- .pre-commit
- doc/developer_guide.md
Added feature: pre-commit 
closes #401
checks against flake8 and black for now. 
@spbnick Is this the correct method? Which one should we add and (possibly remove ) in this?
Also, we will require to make changes in documentation and specify the user to use the pre-commit install cmd after installation.
PS: pre-commit black changed the formatting. If it is not required we can remove that.
> Add pre-commit hook script

- kcidb/test_monitor.py
Increase timeout for receiving generated emails in test_email_generated (back) to 30 minutes to handle the occasional PostgreSQL disconnects and message queue delivery retries, which take a while.
A better fix would be to make the PostgreSQL driver retry queries, but it's not a trivial task and would take a bit to implement.
> tests: Increase email timeout to handle disconnects

- get-url-stats
This is the kcidb test result field info extracting script which will save the results in a csv file 
To run 
```python3 script.py <test file.json> > <output file.csv>```
> kcidb test result field info extracting script

- conftest.py
> Moved empty_deployment fixture to session scope in conftest

- cloud
Added `updated_urls_topic` to the cloud function environment.
> cloud: Add updated_urls_topic to cloud function env

- cloud
Added `cloud_function_withdraw "$project" "${prefix}cache_urls" ` to the withdrawing section in the cloud script. Before it was not withdrawing it only deploying it. 
> cloud: Add kcidb_cache_urls to cloud func withdraw

- kcidb/cache/__init__.py
reformat public url return value in `_format_public_url` of `cache` client. This will fix the white spaces that were leading in the redirection URL generated by `_format_public_url`
> reformat public url return value

- cloud
- main.py
- requirements.txt
- setup.py
Added cache redirection server function.
> cloud: Add cache_redirector function

- cloud
Restructure and documented cache bucket, also added the function deployment region variable.
> cloud: Restructure and documented cache bucket

- doc/_index.md
As the documentation in kernelci-project is being updated to cover the new API & Pipeline, some content is being moved to a Legacy section. As a result, consolidate the KCIDB documentation on the KCIDB section main page to decouple it from the rest of the rework.
There is now a direct mention of KCIDB on the documentation landing page on kernelci.org/doc with the overall KernelCI architecture diagram.  Then most of the KCIDB-specific parts are now being moved to the KCIDB section.  Once all the changes have landed, we might revisit this again and add KCIDB mentions in more places if needed.
Depends on https://github.com/kernelci/kernelci-project/pull/230
Depends on https://github.com/kernelci/kernelci-project/pull/232
> doc: add content from legacy documentation in kernelci-project

- cloud
Wait for the cloud_sql_proxy to become ready before running the command that's supposed to use it. This prevents command failures in times of higher load, when the proxy takes a bit to start, authenticate, and connect.
> cloud: Wait for PostgreSQL proxy to become ready

- kcidb/mq/__init__.py
- main.py
This fixes the submission queue blockage due to invalid messages not being safely discarded, trying to make their way into the database, failing, and aborting the `kcidb_load_queue` Cloud Function. We've had this problem before, and it resurfaced because of refactoring of I/O validation. There's now an [issue](https://github.com/kernelci/kcidb/issues/460) about making a test for this.
> Fix invalid message processing

- cloud
Increased max instances and reduced timeout for the `kcidb_cache_redirect` cloud function.
> Update in increase max instances and reduce timeout for kcidb_cache_redirect

- kcidb/__init__.py
Currently all the KCIDB submission APIs are synchronous, meaning we have
network latency in the call which isn't ideal for large numbers of small
submissions. The underlying BigQuery PubSub APIs offer an API based on
futures which should hopefully allow us to do better here, allowing the
client to submit data and then later check that it has actually been sent
so that the PubSub library can batch I/O or do it asynchronously.
This is already wired up at the publisher level so just add a top level
client method which exposes the future based API. We may want to also
expose something of the flow control parameters via the PublishFlowControl
passed when creating the client, though the current defaults (1000 messages
and 10Mb in flight) look reasonable.
Signed-off-by: Mark Brown …
> client: Expose future based submissions

- cloud
Add support for deploying and withdrawing specific Cloud Functions, so we could speed up develop/deploy/test loop.
Includes a bunch of requisite changes as well as a few minor somewhat-related improvements.
> Support deploying and withdrawing specific Cloud Functions

- cloud
Now that our BigQuery dataset is so large (and not partitioned), and costs a lot to query, stop giving submitters permissions for accessing it. We'll have to think of something else. E.g. giving access to PostgreSQL.
> cloud: Stop giving BigQuery access to submitters

- .github/workflows/deploy.yml
The production deployment can't cope with the updates queue, the notification generation times out. This is possibly due to the PostgreSQL database being too big for the resources we have. Mute the updates until we reduce the database size by purging old data a little later.
> Actions: Mute updates in production

- doc/_index.md
Part of https://gitlab.com/cki-project/documentation/-/issues/77
>  Use explict documentation page aliases for CKI docs

- kcidb/monitor/spool/__init__.py
> Update firestore filtering

- .github/workflows/deploy.yml
- .github/workflows/test.yml
- kcidb/db/postgresql/__init__.py
- kcidb/db/postgresql/schema.py
- kcidb/db/postgresql/v04_00.py
- kcidb/db/postgresql/v04_03.py
- kcidb/db/sql/schema.py
Add indexes on all _timestamp columns in a new v4.3 PostgreSQL schema, so that we can run queries to decide purging cut-off, in finite time, as well as speed up actual purges.
> Add timestamp indexes

- kcidb/templates/incident.j2
- kcidb/templates/issue.j2
- test_kcidb.py
> test_kcidb: Add tests for kcidb-ingest

- cloud
- kcidb/cloud/cloud_functions.sh
- kcidb/cloud/password.sh
- kcidb/cloud/psql.sh
- kcidb/cloud/pubsub.sh
- kcidb/cloud/scheduler.sh
- kcidb/cloud/secrets.sh
- kcidb/cloud/sections.sh
- kcidb/misc.py
- kcidb/mq/__init__.py
- kcidb/test_misc.py
- main.py
- test_main.py
Add a cloud function and a cloud scheduler job for purging the operational database of data that is older than six months, rounded down to month boundary.
> Implement operational database purging

- kcidb/db/postgresql/__init__.py
- kcidb/db/postgresql/v04_04.py
- kcidb/misc.py
Attempt to improve notification performance by sprinkling some indexes onto the PostgreSQL database.
> Sprinkle indexes on PostgreSQL

- kcidb/db/postgresql/v04_00.py
The bare 'RETURN' statement in get_version() is caught as a syntax error by PostgreSQL 12.x. Return the integer literal using a simple SQL statement instead.
**NOTE**: Not tested with other PostgreSQL versions.
> postgresql: fix get_version() for older PostgreSQL versions

- tests.yaml
Add KernelCI tests to test catalogue as per KCIDB norms.
> tests.yaml: add KernelCI-specific tests

- tests.yaml
Rename `kernelci_tast` to `tast` as it is a known test suite from ChromeOS and not specific to KernelCI. Update test suite link as well.
> tests.yaml: rename `kernelci_tast` test

- kcidb/mq/__init__.py
Discard messages with strings containing NUL characters in the kcidb.mq.IOSubscriber. This will help us clear a submission queue containing a number of such messages at the moment, but should be done inside the I/O JSON schema instead.
See https://github.com/kernelci/kcidb-io/issues/79
> mq: Discard messages with strings containing NUL

- .github/workflows/test.yml
- .pre-commit
- kcidb/__init__.py
- kcidb/db/__init__.py
- kcidb/misc.py
- kcidb/mq/__init__.py
- kcidb/oo/__init__.py
- requirements.txt
- setup.py
Switch to the v1.7.0.post1 version of our fork of jq.py, based on the upstream v1.7.0 release.
That release supports Python 3.12, and uses a newer release of jq, one where it's now necessary to explicitly request support for parsing RS-separated JSON (matching RFC 7464 and "application/json-seq" media type). So replace the `--seq` command-line option with two: `--seq-in` and `--seq-out` enabling RS separation in the input and the output respectively (but keep `--seq` as an alias for the latter).
> Switch to jq.py v1.7.0

- doc/submitter_guide.md
CKI had this chart for a while in https://cki-project.org/docs/test-maintainers/status-meaning/ and it's been useful for explaining ownership!
> Add flowchart about the status ownership and mention "running" around the absent status

- tests.yaml
As KCI baseline tests are actually boot tests, we'll be referring these tests as `boot` from now on.
> tests.yaml: remove `kernelci_baseline`

- cloud
- kcidb/cloud/functions.sh
- test_main.py
Remove loading submissions into BigQuery until we come up with a way to increase throughput (likely pulling chunks from PostgreSQL). This should help us deal with the backlog in production submission queue.
We might also need to either switch to direct triggering of Cloud Functions by messages from the queue, to reduce latency, or simply switch to a persistent Cloud Run service.
Concerns: https://github.com/kernelci/kcidb/issues/541
> cloud: Load submissions into PostgreSQL only, faster

- kcidb/monitor/subscriptions/linux_stable_rc.py
- kcidb/oo/__init__.py
- kcidb/templates/stable_rc_build.j2
- kcidb/templates/stable_rc_revision.j2
- kcidb/templates/stable_rc_revision_description.txt.j2
- kcidb/templates/stable_rc_revision_summary.txt.j2
- kcidb/templates/stable_rc_test.j2
- kcidb/test_monitor.py
Closes https://github.com/kernelci/kcidb/issues/532
Add a subscription script for generating notifications for Linux `stable-rc` tree. Also, add a test method to `kcidb/test_monitor.py` for the same.
> Linux `stable-rc` subscription

- kcidb/cloud/functions.sh
Halve the number of instances of kcidb_spool_notifications() Cloud Functions, to smoothen out PostgreSQL load, avoid timeouts, and lower costs.
> cloud: Halve notification spooling instances

- kcidb/templates/stable_rc.j2
- kcidb/templates/stable_rc_build.j2
- kcidb/templates/stable_rc_revision_description.txt.j2
- kcidb/templates/stable_rc_test.j2
- Fix boot tests overview
- Handle missing build architecture and config for build failure summary
- Only take into account results from `maestro` and `broonie` CI systems as of now
-  Add `Also checked out from` tag in `REVISION` section to list checkout URL with the same commit from trees other than `stable-rc`
> Fix `stable-rc` report

- kcidb/templates/stable_rc_test.j2
Fix an issue of empty section for boot failures. This was due to the use of an incorrect test node field for getting `platform` information.
Use `environment.misc.platform` to fix the issue.
Also, display the below message when boot failures are found without failure information:
```
Boot failures found but failure information missing
```
So, now the boot failures would look like:
```
BOOT TESTS
Failures
Boot failures found but failure information missing
CI system: broonie
x86_64:(x86_64_defconfig)
-acer-cbv514-1h-34uz-brya
CI system: maestro
```
> stable-rc: fix empty `BOOT TESTS` section

- kcidb/templates/stable_rc_revision_description.txt.j2
Fix list displayed in `Also checked out from` for checkout without git repository URL.
Such as:
https://kcidb.kernelci.org/d/checkout/checkout?orgId=1&var-datasource=production&var-origin=All&var-build_architecture=All&var-build_config_name=All&var-id=broonie:1e7748be65d242138e8bf9f2ca2d7a07
> stable-rc: fix other repo list

- kcidb/templates/stable_rc_test.j2
Fix the below error while displaying boot failures when related build architecture information not found:
```
File "/workspace/kcidb/templates/stable_rc_test.j2", line 22, in template
{% for architecture, tests in boot_tests|groupby("build.architecture") %}
File "/layers/google.python.pip/pip/lib/python3.9/site-packages/jinja2/async_utils.py", line 45, in wrapper
return normal_func(*args, **kwargs)
File "/layers/google.python.pip/pip/lib/python3.9/site-packages/jinja2/filters.py", line 1261, in sync_do_groupby
for key, values in groupby(sorted(value, key=expr), expr)
TypeError: '<' not supported between instances of 'str' and 'NoneType
```
> stable-rc: fix `BOOT TESTS` section

- kcidb/templates/stable_rc_test.j2
Improve formatting and avoid repetition of same platform name for specific architecture for boot failures.
> stable-rc: improve boot failures formatting

- kcidb/cloud/functions.sh
- kcidb/cloud/psql.sh
Reduce the instances of notification-spooling Cloud Functions to just two to reduce the load on PostgreSQL, and double their memory, as they're hitting the current limit quite often now.
Revoke the default permission to create object in the public schema of each KCIDB database in PostgreSQL. That permission is granted per-user, and the default was overlooked until recently.
Supply the currently-used PostgreSQL instance settings when creating, so we don't lose them.
> Tune notification spooling

- tests.yaml
Add test to verify basic WiFi functionality on Chromebooks.
> tests.yaml: add `kernelci_wifi_basic`

- kcidb/templates/stable_rc_test.j2
List CI system with every boot failure per architecture.
> stable-rc: improve CI system details for boot failures

- kcidb/templates/stable_rc_build.j2
In some cases, build architecture information is not available for failed builds.
Do not list down such builds in the failures section as it won't be meaningful if such information is not present.
> stable-rc: fix empty build failure section

- kcidb/templates/stable_rc.j2
- kcidb/templates/stable_rc_build.j2
- kcidb/templates/stable_rc_test.j2
In the Boot failures section, use `, ` separator for different build configs for a build architecture for better readability.
Boot failures such as:
```
BOOT TESTS
Failures
x86_64:(cros://chromeos-6.6/x86_64/chromeos-amd-stoneyridge.flavour.configcros://chromeos-6.6/x86_64/chromeos-intel-pineview.flavour.configx86_64_defconfig)
-hp-x360-14a-cb0001xx-zork
-asus-CM1400CXA-dalboz
CI system: maestro
```
It would look like the below:
```
BOOT TESTS
Failures
x86_64:(cros://chromeos-6.6/x86_64/chromeos-amd-stoneyridge.flavour.config, cros://chromeos- 
6.6/x86_64/chromeos-intel-pineview.flavour.config, x86_64_defconfig)
-hp-x360-14a-cb0001xx-zork
-asus-CM1400CXA-dalboz
CI system: maestro
```
> stable-rc: separate build configs with `, `

- kcidb/monitor/subscriptions/linux_stable_rc.py
Generate report only if at least one revision is found from selected origins i.e. `maestro` or `broonie`.
> stable-rc: do not generate empty reports

- kcidb/monitor/output.py
- kcidb/monitor/subscriptions/codec_summary.py
- kcidb/monitor/test_output.py
- kcidb/templates/common.j2
- kcidb/templates/fluster_revision.j2
- kcidb/templates/fluster_revision_description.txt.j2
- kcidb/templates/fluster_revision_summary.txt.j2
- kcidb/templates/fluster_test.j2
Generate codec summary report and email notifications for the same.
Created on top of https://github.com/kernelci/kcidb/pull/565 to use `common.j2`.
> Codec summary report

- kcidb/templates/fluster_revision_description.txt.j2
Include `tree` and `branch` for accurate test report link.
> Update fluster test report link

- kcidb/monitor/output.py
- kcidb/monitor/subscriptions/linux_omap.py
- kcidb/monitor/subscriptions/linux_stable_rc.py
- kcidb/templates/stable_rc_revision_description.txt.j2
Enable automated test report for `omap` tree.
> `omap` notification subscription

- .github/workflows/deploy.yml
This will stop notifications working on production.
CC @JenySadadia, am I right that we have no notifications sent to maintainers ATM?
I'll need to fix the performance, which I've been working on before LPC, but now I gotta get rid of COVID first.
> cloud: Mute updates to relieve PostgreSQL temporarily

- .github/workflows/deploy.yml
Re-enable updates (and thus notification generation) in both production and playground. This merely records the state for the future deployments, as the updates were enabled manually earlier today.
> Re-enable updates, and thus notifications

- kcidb/db/__init__.py
- kcidb/db/abstract.py
- kcidb/db/bigquery/v04_00.py
- kcidb/db/bigquery/v04_02.py
- kcidb/db/misc.py
- kcidb/db/mux.py
- kcidb/db/null.py
- kcidb/db/postgresql/schema.py
- kcidb/db/postgresql/v04_00.py
- kcidb/db/postgresql/v04_02.py
- kcidb/db/postgresql/v04_05.py
- kcidb/db/schematic.py
- kcidb/db/sql/schema.py
- kcidb/db/sqlite/schema.py
- kcidb/db/sqlite/v04_00.py
- kcidb/db/sqlite/v04_02.py
- kcidb/monitor/spool/__init__.py
- kcidb/test_db.py
> Support time range dump

- kcidb/cloud/functions.sh
- kcidb/db/__init__.py
- kcidb/db/abstract.py
- kcidb/db/bigquery/v04_00.py
- kcidb/db/mux.py
- kcidb/db/null.py
- kcidb/db/postgresql/v04_00.py
- kcidb/db/schematic.py
- kcidb/db/sql/schema.py
- kcidb/db/sqlite/v04_00.py
- kcidb/test_db.py
- main.py
Now that we're not going to be loading data in KCIDB directly from the submission queue, remove the rate throttling (which was inactive anyway due to particular database drivers being used).
Instead solely targeting the get_last_modified() method to databases which have load rate limit, make all of them support it, and return the maximum `_timestamp` value across all tables, if the schema has it.
Concerns #541
> Get last modified from data

- kcidb/monitor/subscriptions/codec_summary.py
Add checks for fluster tests to avoid generating emails with "No tests found".
> Codec summary report: handle "No tests found"

- kcidb/templates/fluster_test.j2
Maestro runs fluster tests on debian and chromeos. Include summary of chromeos tests as well in the
codec summary report.
> codec-summary report: include chromeos fluster tests

- kcidb/db/__init__.py
- kcidb/db/abstract.py
- kcidb/db/bigquery/v04_00.py
- kcidb/db/mux.py
- kcidb/db/null.py
- kcidb/db/postgresql/v04_00.py
- kcidb/db/schematic.py
- kcidb/db/sql/schema.py
- kcidb/db/sqlite/v04_00.py
- kcidb/test_db.py
- main.py
- test_main.py
At the moment all operational tables are archived using a single timestamp for the lower boundary, which either loses us data, if they're uneven, or forces us to load duplicates to make sure we don't lose anything. This is because some databases don't support atomic modifications of multiple tables at once.
Work that around, by assigning separate time ranges to separate tables, when dumping.
Concerns #541
> Archive each table independently

- kcidb/templates/fluster_test.j2
Fix the issue in fluster test report formatting.
It currenly reports all the tests one by one instead of the summary with file system.
Fixes: 6656ef2("codec-summary report: include chromeos fluster tests")
> Codec summary report: fix report formatting

- kcidb/cloud/scheduler.sh
- main.py
- test_main.py
Support receiving archiving parameters from the trigger event, and remove the duration limit on archived data. Only limit the runtime, editing window, and chunk duration.
> cloud: Archive according to parameters

- kcidb/db/bigquery/v04_00.py
- test_main.py
Disable query caching when dumping data from BigQuery in an attempt to fix the database purging test (test_purge_db()).
Revert if there's no effect on test stability.
> Try fixing test_purge_db()

- kcidb/cloud/functions.sh
Bump the RAM allocated to the data archival cloud function from 4GB to 8GB, so we avoid aborting on out-of-memory when transferring 12 hours of data at a time.
It could be that BigQuery is accumulating memory use over time and running out, despite us calling gc.collect() after every transfer, but I don't have the time to pursue this further.
> cloud: Bump archival RAM to (the max of) 8GB

- kcidb/monitor/subscriptions/codec_summary.py
- kcidb/monitor/subscriptions/linux_stable_rc.py
- kcidb/monitor/subscriptions/linux_stable_rt.py
Add a check to verify if there are builds from selected origins before generating the report.
> Fix empty reports: `stable-rc`, `stable-rt`, `fluster`

- tests.yaml
This is more "canary" or PoC test, than real test, also by some reason it often gives false positives, not adding any value.
We decided it is better to remove it.
> (tests.yaml): Remove kver tests

- .github/workflows/deploy.yml
- cloud
- doc/administrator_guide.md
- kcidb/cloud/functions.sh
- main.py
Disable posting object/URL updates to the corresponding queues to reduce Cloud Function load, which saw a cost hike.
This will disable notifications and trial artifact archival.
> Disable posting object/URL updates

- kcidb/__init__.py
As we implemented kcidb-rest interface on server side, we need to make optional (for now) support for it in client library.
> Add initial REST support
