kernelci/kcidb

README.md
Add a link to the Google instructions to set up a BigQuery account and
data set, as well as some quick start steps.
Signed-off-by: Guillaume Tucker <guillaume.tucker@collabora.com>
=> README.md: add instructions to create BQ account

kcidb/__init__.py
Fix a few issues uncovered by data submitted from Kernel CI.
=> Fix data transformations

kcidb/db_schema.py, kcidb/io_schema.py
Signed-off-by: Kevin Hilman <khilman@baylibre.com>
=> schema: add git branch, describe

kcidb/__init__.py, setup.py
Add a "kcidb-validate" tool to make it easier to validate the I/O data
without submitting it, exactly the way the submitting would.
=> Add kcidb-validate

tests.yaml
Catalog a test signifying the kernel booted successfully. Call it "boot".
=> tests: Add boot test

kcidb/__init__.py, setup.py
Add an implementation of message queue management tools.
Squeeze in a fix for the previous change.
=> Implement message queue management tools

.travis.yml, README.md, kcidb/__init__.py, kcidb/misc.py, kcidb/oo/__init__.py, kcidb/oo/build.py, kcidb/oo/build_description.txt.j2, kcidb/oo/build_macros.j2, kcidb/oo/build_summary.txt.j2, kcidb/oo/misc.py, kcidb/oo/revision.py, kcidb/oo/revision_description.txt.j2, kcidb/oo/revision_macros.j2, kcidb/oo/revision_summary.txt.j2, kcidb/oo/test.py, kcidb/oo/test_description.txt.j2, kcidb/oo/test_macros.j2, kcidb/oo/test_summary.txt.j2, kcidb/subscriptions/__init__.py, kcidb/subscriptions/ltp_maintainers.py, kcidb/subscriptions/rdma.py, kcidb/test_oo.py, setup.py
Add support for OO representation of I/O data to support report formatting and subscriptions.
Add draft subscription implementation.
=> Add OO representation and subscriptions

.gitignore, README.md, kcidb/__init__.py, kcidb/db/__init__.py, kcidb/misc.py, kcidb/mq/__init__.py, kcidb/spool/__init__.py, kcidb/subscriptions/__init__.py, kcidb/subscriptions/ltp_maintainers.py, kcidb/subscriptions/rdma.py, kcidb/subscriptions/test.py, kcidb/test_misc.py, kcidb/test_subscriptions.py, main.env.yaml, main.py, requirements.txt, setup.py
This is a bunch of dirty work to make report sending work.
=> Make report sending work

kcidb/__init__.py, kcidb/db/__init__.py, kcidb/misc.py, test_setup.py
Add support for logging, with only DB queries logged for now.
=> Add support for logging

kcidb/__init__.py, kcidb/db/__init__.py
This fixes notification generation timeouts in Google Cloud Functions.
=> Accelerate complements

.travis.yml, kcidb/io/schema/misc.py, kcidb/tests/schema.py, requirements.txt, setup.py
=> Enable JSON schema format checking

kcidb/io/__init__.py, test_kcidb.py
=> Add kcidb.*_main() tests

kcidb/subscriptions/linux_stable.py, kcidb/subscriptions/mainline.py
(cherry picked from commit 6e666f51220fa90bde12ea187e6aa7c67517e219)
=> Ignore syzbot in subscriptions

kcidb/__init__.py, kcidb/db/__init__.py, kcidb/mq/__init__.py
=> Explicitly validate data from the outside world

.travis.yml, kcidb/__init__.py, kcidb/db/__init__.py, kcidb/misc.py, kcidb/monitor/__init__.py, kcidb/monitor/misc.py, kcidb/monitor/output.py, kcidb/monitor/spool/__init__.py, kcidb/monitor/subscriptions/__init__.py, kcidb/monitor/subscriptions/linux_stable.py, kcidb/monitor/subscriptions/ltp_maintainers.py, kcidb/monitor/subscriptions/mainline.py, kcidb/monitor/subscriptions/test.py, kcidb/monitor/test_output.py, kcidb/monitor/test_spool.py, kcidb/mq/__init__.py, kcidb/oo/__init__.py, kcidb/oo/misc.py, kcidb/test_monitor.py, main.py, playground.env.yaml, requirements.txt, setup.py, test_kcidb.py, test_main.py
=> Default heavy asserts off

requirements.txt, setup.py
=> Upgrade to kcidb-io v2

kcidb/db/bigquery/__init__.py
Deduplicate objects when querying/dumping via the bigquery driver, to
match sqlite (and potential other) driver's behavior of not having
duplicate objects.
=> bigquery: Deduplicate objects

kcidb/mq/__init__.py, requirements.txt, setup.py
Fix #110 
Unpin google-cloud pubsub
Fix bug issue on google cloud pubsub create topic
=> [Close #110] Upgrade google-cloud pubsub dependency

kcidb/db/bigquery/__init__.py
=> Add single function for querying BigQuery

kcidb/__init__.py
#76 Make Kcidb-schema output older schema versions on request. @spbnick , kindly review
=> Make Kcidb-schema output older schema versions on request

kcidb/db/__init__.py, kcidb/test_db.py, setup.py
Fix #234 
1) Remove the kcidb-db-complement command
=> [Close #234] Drop kcidb-db-complement and the underlying functions #234

doc/submitter_guide.md
Fixup/update a few small things in the Submitter Guide.
=> Fixup submitter guide

kcidb/__init__.py, test_kcidb.py
Close #145 
- Add print to kcidb-validate to output reports after they were validated
=> Consider making kcidb-validate output validated reports in kcidb-validate  #145

.github/workflows/deploy.yml, .github/workflows/test.yml
close #265
Create a workflow for check deployment
Add command to deploy to staging and production
=> deploy: Deploy main commits to staging #256

.github/workflows/deploy.yml, .github/workflows/test.yml
Check that repeated deployment and withdrawing don't break, in GitHub
actions.
=> Actions: Do double deploy/withdraw

kcidb/test_orm.py
@spbnick 
This is the PR that contains the added test for `kcidb.orm` module.
Please review
=> Addition to kcidb.orm test

cloud, main.py
close #61
1. Remove extra whitespace and args
2. Explicitly pass trigger_topic to scheduler_withdraw
3. Remove extra args to scheduler_job_withdraw
4. Pick notification
=> pick abandoned notification #61

.github/workflows/deploy.yml, .github/workflows/test.yml
close #265 
1) Change test.yml to a reusable workflow 
2) Make deploy.yml call test.yml workflow 
3) Change triggers call for all the workflows
=> Actions: Make test workflow reusable and call it from deploy

.github/workflows/deploy.yml
close #265
fix shell syntax issue in deploy workflow
=> Actions: Fix shell syntax issue in deploy workflow 

.github/workflows/deploy.yml, .github/workflows/test.yml
=> Actions: explicitly pass secrets to the called test workflow

cloud
=> cloud: Update pick_notifications_trigger job to deploy every 30 minutes

.github/workflows/deploy.yml
=> Actions: remove extra submitter options to deploy cloud

cloud, kcidb/monitor/output.py, kcidb/monitor/spool/__init__.py, kcidb/monitor/subscriptions/mark_brown.py, kcidb/test_monitor.py
close #264
Add implementation for delayed notification
=> Implement delayed notifications #264

kcidb/monitor/output.py
=> monitor: Truncate notification subject and message to char limit

kcidb/monitor/output.py, kcidb/monitor/test_output.py
=> monitor: Remove invalid notification subject character

doc/submitter_guide.md, kcidb/__init__.py, kcidb/db/__init__.py, kcidb/db/bigquery/__init__.py, kcidb/db/bigquery/schema.py, kcidb/db/json/__init__.py, kcidb/db/misc.py, kcidb/db/null/__init__.py, kcidb/db/sqlite/__init__.py, kcidb/db/sqlite/schema.py, kcidb/misc.py, kcidb/monitor/test_output.py, kcidb/mq/__init__.py, kcidb/orm/__init__.py, kcidb/test_db.py, kcidb/test_monitor.py, kcidb/test_mq.py, kcidb/test_orm.py, requirements.txt, setup.py, test_kcidb.py
=> Tie KCIDB to V4 i/o schema

.gitignore, kcidb/test_oo.py
=> Implement kcidb.oo test

kcidb/mq/__init__.py, kcidb/oo/__init__.py
=> Error in the CI

kcidb/oo/__init__.py
=> oo: Switch 'fail' and 'error' status priority

kcidb/oo/__init__.py, kcidb/test_oo.py
=> tests: Add more kcidb.oo test

kcidb/db/bigquery/__init__.py, kcidb/db/sqlite/schema.py, kcidb/misc.py, kcidb/monitor/spool/__init__.py
This introduces a host of minor fixes and improvements done during the work on table partitioning and query time-limiting.
=> Misc fixes

kcidb/db/postgresql/schema.py
=> postgresql: Fix errors in docs

kcidb/test_oo.py
=> More test cases for oo module

.github/workflows/deploy.yml, .github/workflows/test.yml, cloud, kcidb/db/__init__.py, kcidb/db/misc.py, kcidb/db/null/__init__.py, kcidb/db/postgresql/__init__.py, kcidb/db/sqlite/__init__.py, kcidb/misc.py, kcidb/oo/__init__.py, kcidb/orm/__init__.py, kcidb/test_db.py, kcidb/test_oo.py, main.py, test_main.py
Implement deploying a PostgreSQL instance and uploading data
simultaneously to a PostgreSQL database and a BigQuery dataset, while
only using the former for generating notifications. Double the loading
function memory, as we started running out of memory with this setup.
This should help us save a lot on BigQuery queries, since only the
dashboard will be using that now.
Fixes #209
=> cloud: Deploy PostgreSQL

cloud, kcidb/misc.py, main.py
=> Reduce spooling load

cloud
fix #371 
added support for specifying a value for PYTHONOPTIMIZE
@spbnick Need reviews
=> feat: added support for specifying a value for PYTHONOPTIMIZE

kcidb/__init__.py, kcidb/db/__init__.py, kcidb/test_db.py, test_kcidb.py
This PR closes #398 
@spbnick need reviews
=> Support querying issues and incidents with kcidb(-db)-query.

.github/workflows/deploy.yml
Enable Python code optimization (removal of assertions) in Playground, as a test before enabling it in Production.
=> Optimize Python code in Playground

kcidb/db/bigquery/v04_00.py
closes #378 
Silence the deprecation warnings and switch to the new BigQuery dataset access API
=> Switch to new BigQuery dataset access API

cloud
Adding cache client function deployment support in cloud script. Need reviews @spbnick
=> Add cache client function deployment support

cloud
Cloud storage deployment support.
=> cloud: add storage support

cloud, main.py
Added `storage_bucket` to cloud functions environment so that cache client can use that bucket name and store the artifacts in there.
=> cloud: Add storage_bucket to cloud functions env

cloud
Added a check for bucket before creation.
=> Add check for bucket existence before creation

cloud
=> cloud: Add -q to storage_deploy IAM command

kcidb/mq/__init__.py
Add Publisher/Subscriber classes for cache topic.
=> Add Publisher/Subscriber classes for cache topic

cloud, conftest.py, kcidb/mq/__init__.py, test_main.py
Added cache client whole workflow test, need reviews @spbnick
=> tests for caching system

tests.yaml
Add a mapping for KUnit.
Signed-off-by: Mark Brown <broonie@kernel.org>
=> tests: Add KUnit

kcidb/cache/__init__.py, main.py, test_main.py
This support add extracting urls from the I/O data and publish them to cache topic. This PR also includes modified test to test caching on urs from the I/O data.
=> Added support for caching urls from I/O data

kcidb/__init__.py
The previous function had not been tested due to difficulties with test
setups, fix the name of the function for future submission.
Signed-off-by: Mark Brown <broonie@kernel.org>
=> submit: Use correct function for future submissions

kcidb/cache/__init__.py
=> cache: Add debug logging to cache client's store method

doc/administrator_guide.md
Added cache system documentation, Need reviews @spbnick
=> Add cache system documentation

doc/submitter_guide.md, kcidb/db/bigquery/v04_01.py, kcidb/db/postgresql/v04_01.py, kcidb/db/sqlite/v04_01.py, kcidb/io.py, kcidb/oo/__init__.py, kcidb/templates/misc.j2, kcidb/templates/test.j2, kcidb/test_db.py
Add support for I/O schema v4.2, which adds another test status: "MISS".
=> Support I/O schema v4.2

tests.yaml
to be used as universal_id in kpet-db
=> add libevdev

kcidb/db/postgresql/__init__.py, kcidb/db/postgresql/v04_06.py
Add PostgreSQL schema v4.6 adding more indexes to help Grafana dashboards.
=> postgresql: Add schema v4.6 with more indexes

tests.yaml
Add a test suite for Device tree checks.
=> tests.yaml: add `dtbs_check` test

tests.yaml
Add KernelCI Watchdog reset test suite.
=> tests.yaml: add `kernelci_watchdog_reset` test

.pre-commit, cloud, kcidb/cloud/artifacts.sh, kcidb/cloud/iam.sh, kcidb/cloud/iss-ed, kcidb/cloud/iss-ed.Dockerfile, kcidb/cloud/pubsub.sh, kcidb/cloud/run.sh, kcidb/issue_editor/__init__.py, requirements.txt, setup.py
Heads-up @helen-fornazier. This is WIP ATM.
=> Add dummy issue editor service and package

tests.yaml
=> tests.yaml: add `rt-tests`

kcidb/db/postgresql/__init__.py, kcidb/db/postgresql/v04_07.py
Add PostgreSQL schema v4.7 adding a bunch more indexes, mostly for issues and incidents.
Concerns https://github.com/kernelci/kcidb/issues/545
=> postgresql: Add schema v4.7 with a bunch more indexes

kcidb/monitor/subscriptions/linux_stable_rt.py
Add `stable-rt` maintainer mailing list and `Helen Mae Koike Fornazier` from Collabora to email recipients.
=> `stable-rt` report: update email recipients

doc/administrator_guide.md, doc/developer_guide.md, doc/subscriber_guide.md
Explain KCIDB email notifications.
=> doc/developer_guide: add `Email notifications` section

kcidb/monitor/subscriptions/linux_stable_rc.py
Add me back there, as I'll be following those results and reports from now on.
=> subscriptions: add Gustavo to the stable-rc notifications

kcidb/db/postgresql/v04_00.py
This is trying to resolve deadlocks between loading processes
=> db: postgresql: Sort loaded objects to avoid deadlocks

kcidb/db/bigquery/__init__.py, kcidb/db/bigquery/v05_03.py, kcidb/db/postgresql/__init__.py, kcidb/db/postgresql/v05_03.py, kcidb/db/sqlite/__init__.py, kcidb/db/sqlite/v05_03.py, kcidb/io.py, kcidb/test_db.py
*REQUIRES*: https://github.com/kernelci/kcidb-io/pull/99
=> Support I/O schema v5.3
